name: Build LaTeX PDF

on:
  push:
    branches: ["**"]
  pull_request:
    branches: ["**"]

jobs:
  build-pdf:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Compile LaTeX
        uses: xu-cheng/latex-action@v3
        with:
          root_file: report.tex
          latexmk_use_xelatex: true
          latexmk_shell_escape: true
          extra_system_packages: biber
          pre_compile: tlmgr update --self && tlmgr install biblatex biber csquotes siunitx circuitikz

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: report-pdf
          path: report.pdf


