name: Build LaTeX PDF

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  build-pdf:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Diagnose workflow start
        run: |
          echo "Workflow triggered on $GITHUB_REF at commit $GITHUB_SHA"

      - name: Show environment
        run: |
          uname -a
          which xelatex || true
          which latexmk || true
          which biber || true
          tlmgr --version || true

      - name: Compile LaTeX
        uses: xu-cheng/latex-action@v3
        with:
          root_file: report.tex
          latexmk_use_xelatex: true
          latexmk_use_biber: true
          latexmk_shell_escape: true
          extra_system_packages: biber
          pre_compile: tlmgr update --self && tlmgr install biblatex biber biblatex-ieee csquotes siunitx circuitikz lm pgfplots babel-english

      - name: List workspace files
        if: always()
        run: |
          ls -la
          echo "Report exists?"; [ -f report.pdf ] && echo yes || echo no

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: vco-report-pdf
          path: report.pdf

      - name: Upload logs (always)
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: vco-report-logs
          path: |
            report.log
            report.bcf*
            report.bbl*
            report.fls
            report.fdb_latexmk

  release:
    # Auto-release on every push (optional: restrict to main)
    if: github.event_name == 'push'
    runs-on: ubuntu-latest
    needs: build-pdf
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: vco-report-pdf
          path: dist
      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: build-${{ github.run_number }}
          name: Automated Build ${{ github.run_number }}
          generate_release_notes: true
          files: dist/report.pdf

  build-tectonic:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      # Removed deprecated/unavailable action 'tectonic-typesetting/tectonic-action'.
      # If Tectonic is desired, replace with a maintained action or install via package manager.


